name: CI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests and coverage
        run: |
          export PRIVATE_KEY="0000000000000000000000000000000000000000000000000000000000000001"
          yarn install --ignore-scripts
          yarn test
          yarn coverage
      - name: Post coverage report
        uses: eleboys/test-coverage-report-action@v1.0.2
        id: report
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./coverage.json
          title: Solidity Test Coverage
      - name: Print coverage report
        run: echo "Report coverage json ${{ steps.report.outputs.summary }}"
